version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: atoll-lightning-server_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/forge0x/lightning-server:0.2.0
    restart: on-failure
    environment:
      NODE_ENV: production
      PORT: "3000"
      CONFIG_FILE: /data/config.json
    volumes:
      - ${APP_DATA_DIR}/data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 60s
      start_period: 15s
      timeout: 5s
