version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: atoll-beszel_web_1
      APP_PORT: 8090

  web:
    image: henrygd/beszel:0.18.7
    restart: on-failure
    environment:
      APP_URL: http://${DEVICE_HOSTNAME:-umbrel.local}:8090
    volumes:
      - ${APP_DATA_DIR}/data:/beszel_data
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      interval: 120s
      start_period: 10s
      timeout: 5s
